### ISSUE TITLE
Tela de jogo: definição do layout

### ISSUE THREAD

**Issue by renato-scaroni** [fastfooddapolitica/direitos-e-silencios#10]
falta definição

**Comment by andresmrm** [comment]
Do jeito que está atualmente, em celulares, notei dos possíveis problemas:
- A pessoa não conseguir dar o scroll para o lado. Para dar o scroll é preciso clicar no fundo perto da carta, mas não na carta em si (se não dá o drag). Eu consigo me virar, mas é possível que muitas pessoas não percebam como fazer.
- A pessoa não ver o botão de "verificar cartas", que está mais para baixo. Eu já sei que o botão está lá, mas quem não sabe talvez não veja...
