### ISSUE TITLE
Definir as fontes (tipos de letras)

### ISSUE THREAD

**Issue by andresmrm** [fastfooddapolitica/direitos-e-silencios#17]
Teria que tomar o cuidado de usar fontes livres. Acho que todas desse site são:
https://fontlibrary.org
Aqui há mais opções, mas nem todas livres (acho que dá para filtrar pela licença):
https://www.dafont.com

Elementos textuais (para pensar qual fonte usar para cada):
- título do site (logo)
- título de uma seção de texto (como o "Sobre")
- texto das cartas
- texto corrido comum

Lembrando que quanto mais fontes, maior (de baixar) fica o jogo. Então talvez seja bom usar no máximo 2 fontes (ou 3 se forem pequenas).

**Comment by FastFooddaPolitica-admin** [comment]
Nós usamos prioritariamente a InsaniBurger como título do jogo/ titulo das cartas
e vamos usar a família DIN como suporte, para o restante das coisas.
