### ISSUE TITLE
Definir padrão usado no fundo dos elementos

### ISSUE THREAD

**Issue by andresmrm** [fastfooddapolitica/direitos-e-silencios#20]
Possibilidades:

- manter o ruído atual
- gerar outro ruído: http://noisetexturegenerator.com
- gerar outra coisa, talvez: http://www.tartanmaker.com
- voltar a ser um fundo liso

Usar o mesmo fundo para tudo (como atualmente) ou usar, por exemplo, um para os botões e outro para as telas.

**Comment by FastFooddaPolitica-admin** [comment]
a gente tá usando na nossa campanha um fundo texturizado com bolinhas, vou te mandar o psd com essa textura
