### ISSUE TITLE
Definir se menu in-game continua com está ou criamos um novo

### ISSUE THREAD

**Issue by andresmrm** [fastfooddapolitica/direitos-e-silencios#22]
Atualmente o menu de jogo é simplesmente voltar para a tela inicial. Mantemos assim ou criamos um outro menu?
Se for um outro menu, dependendo das opções que tiver, talvez tenha que ser acessível da tela inicial também, e não apenas de dentro do jogo.

**Comment by FastFooddaPolitica-admin** [comment]
Oi Andres, acho legal ter uma tela inicial do jogo, acredito que podemos usar o ícone do martelinho ilustrado que temos no nosso jogo físico.

Posso te enviar umas propostas.
