### ISSUE TITLE
Definir o conteúdo das cartas

### ISSUE THREAD

**Issue by andresmrm** [fastfooddapolitica/direitos-e-silencios#24]
Nas cartas em papel,
na frente há:
- título
- às vezes outros textos

no verso:
- título (que pode ser diferente do título na frente)
- ano
- outros texto, geralmente meio longos
- às vezes um outro texto em negrito

Em telas pequenas, como celulares, é difícil mostrar tudo isso do jeito que está nas cartas em papel.
Opções:
1. Mostrar só os títulos e ano nas cartas, e transferir o resto para o detalhamento das cartas, que só aparece depois que a carta for virada. (pode acabar faltando informações para ordenar as cartas)
2. Usar uma fonte muito pequena e ilegível e ter alguma forma de dar zoom. (pode ficar difícil comparar as cartas entre si, já que tem que ficar dando zoom a toda hora para ler cada carta)
3. Colocar as cartas bem grandes; em telas pequenas só vai dar para ver uma ou duas cartas por vez. (pode ficar difícil manipular a timeline por ver poucas cartas por vez)
4. Ter uma barra lateral que mostra mais informações da carta sendo arrastada. (pode comer um bom espaço da tela e dificultar a exibição da timeline)

**Comment by FastFooddaPolitica-admin** [comment]
Acho legal esse teste inicial a gente colocar apenas o que realmente é essencial pra pessoa entender a carta. 
Acredito que apenas no caso da carta do aborto, por exemplo e da proibição do parto com algemas é necessário o subtítulo, para situar a pessoa na linha do tempo.

Mas nos avise se ficar muito pequeno!
Nós usamos a fonte InsaneBurger, você tem ela? posso te mandar também!
